### PR TITLE
Update DeveloperGuide Target User Profile and Value Proposition

### LINKED ISSUE #71: Update DG - Target User Profile and Value Proposition
Update the Target User profile along with Value Proposition to match the project direction you have selected.

### PR DESCRIPTION
**Pull request by joshlay96**
- Update Target User Profile in DeveloperGuide
- Update Value Proposition in DeveloperGuide

### CODE REVIEW

**Review by loycatherine — DISMISSED** [review]
Looks alright!

**Review by jwee97 — DISMISSED** [review]
Looks good, thanks!

**Review by loycatherine — DISMISSED** [review]
Better grammar

**Review by zenatrick — APPROVED** [review]
Looks good.

**Pull request merged**
